/**
 * Auto-generated field type mapping from views index
 * This file is generated by index-to-view/generate-field-views.ts
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * Get the field type from a field's viewsIndex
 * @param viewsIndex The views index of the field
 * @returns The field type name
 */
export function getFieldTypeFromViewsIndex(viewsIndex: number): string {
  const viewsIndexToType: Record<number, string> = {
    0: "id",
    1: "virtual",
    2: "text",
    3: "checkbox",
    4: "json",
    5: "relationship",
    6: "timestamp",
    7: "select",
    8: "integer",
    9: "image",
    10: "float",
    11: "document",
    12: "password"
  };

  const fieldType = viewsIndexToType[viewsIndex];
  if (!fieldType) {
    throw new Error(`Invalid views index: ${viewsIndex}`);
  }

  return fieldType;
}